### ISSUE TITLE
Protocol version is incompatible

### ISSUE THREAD

**Issue by isaack0815** [Storj/storjshare-cli#187] opened 2016-10-06 16:35 UTC
Hello, I get since the last update always after the start PREPARING displayed.
In the log file is the following:
{warn} [Thu Oct 06 2016 17:37:01 GMT+0200 (CEST)] you are not publicly reachable, trying traversal strategies...
{warn} [Thu Oct 06 2016 17:37:03 GMT+0200 (CEST)] could not connect to NAT device via UPnP: 36969
{warn} [Thu Oct 06 2016 17:37:03 GMT+0200 (CEST)] failed to map port for tunserver: timeout
{warn} [Thu Oct 06 2016 17:37:03 GMT+0200 (CEST)] could not connect to NAT device via UPnP: 24483
{info} [Thu Oct 06 2016 17:37:03 GMT+0200 (CEST)] node created with nodeID 69736858d31d4a31bd586cdfcff440a1a7bd22da
{info} [Thu Oct 06 2016 17:37:03 GMT+0200 (CEST)] clock is synchronized with ntp, delta: 33
{info} [Thu Oct 06 2016 17:37:04 GMT+0200 (CEST)] requesting probe from nearest neighbor
{info} [Thu Oct 06 2016 17:37:04 GMT+0200 (CEST)] sending PROBE message to {"userAgent":"4.0.0","protocol":"0.9.0","address":"104.196.163.120","port":8443,"nodeID":"593844dc7f0076a1aeda9a6b9788af17e67c1052","lastSeen":1475768224386}
{info} [Thu Oct 06 2016 17:37:04 GMT+0200 (CEST)] received valid message from {"userAgent":"4.0.0","protocol":"0.8.0","address":"104.196.163.120","port":8443,"nodeID":"593844dc7f0076a1aeda9a6b9788af17e67c1052","lastSeen":1475768224786}
{warn} [Thu Oct 06 2016 17:37:04 GMT+0200 (CEST)] Protocol version is incompatible
{warn} [Thu Oct 06 2016 17:37:31 GMT+0200 (CEST)] rpc call fe7b0d774a3b1ea06a133144336999587aa8b6fc timed out
{info} [Thu Oct 06 2016 17:37:31 GMT+0200 (CEST)] requesting tunnelers from neighbor
{info} [Thu Oct 06 2016 17:37:31 GMT+0200 (CEST)] sending FIND_TUNNEL message to {"userAgent":"4.0.0","protocol":"0.9.0","address":"104.196.163.120","port":8443,"nodeID":"593844dc7f0076a1aeda9a6b9788af17e67c1052","lastSeen":1475768251397}
{info} [Thu Oct 06 2016 17:37:31 GMT+0200 (CEST)] received valid message from {"userAgent":"4.0.0","protocol":"0.8.0","address":"104.196.163.120","port":8443,"nodeID":"593844dc7f0076a1aeda9a6b9788af17e67c1052","lastSeen":1475768251876}
{warn} [Thu Oct 06 2016 17:37:31 GMT+0200 (CEST)] Protocol version is incompatible
{warn} [Thu Oct 06 2016 17:38:01 GMT+0200 (CEST)] rpc call 53323cfe119a6b0b6beeb81dd79e1b5a576254f1 timed out
{info} [Thu Oct 06 2016 17:38:01 GMT+0200 (CEST)] requesting tunnelers from neighbor
{info} [Thu Oct 06 2016 17:38:01 GMT+0200 (CEST)] sending FIND_TUNNEL message to {"userAgent":"4.0.0","protocol":"0.9.0","address":"104.196.163.120","port":8445,"nodeID":"593844dc7f0076a1aeda9a6b9788af17e67c1052","lastSeen":1475768281405}
{info} [Thu Oct 06 2016 17:38:01 GMT+0200 (CEST)] received valid message from {"userAgent":"4.0.0","protocol":"0.8.0","address":"104.196.163.120","port":8445,"nodeID":"593844dc7f0076a1aeda9a6b9788af17e67c1052","lastSeen":1475768281797}
{warn} [Thu Oct 06 2016 17:38:01 GMT+0200 (CEST)] Protocol version is incompatible

**Comment by bookchin** [comment] 2016-10-06 16:39
You upgraded before the bridge deployment, give us another day to finish the bridge upgrade and this will resolve itself. 

Closing this since its not a bug, but the desired behavior when communicating with incompatible nodes.

**Closed by bookchin** 2016-10-06 16:39 UTC
