### ISSUE TITLE
Error: EMFILE: too many open files, scandir

### ISSUE THREAD

**Issue by krilson** [Storj/storjshare-cli#206] opened 2016-10-20 12:37 UTC
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
StorjShare: 7.0.1                                           
Core:       4.0.6                                           
Protocol:   0.9.1
```

Replace the values below using the output from `node --version`.

```
v4.4.4
```
### Expected Behavior

It should run 24/7 without me checking if ot works.
### Actual Behavior

Storjshare-cli quits with the following error on random occasions:

Error: EMFILE: too many open files, scandir '/dvatb/storjsha
re/sharddata.kfs'  
    at Error (native)  
    at Object.fs.readdirSync (fs.js:808:18)  
    at Btable.stat (/home/krile/.nvm/versions/node/v4.4.4/li
b/node_modules/storjshare-cli/node_modules/storj-lib/node_mo
dules/kfs/lib/b-table.js:186:21)  
    at /home/krile/.nvm/versions/node/v4.4.4/lib/node_module
s/storjshare-cli/node_modules/storj-lib/lib/storage/adapters
/embedded.js:173:16

```

```
### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.
1. Run storjshare-cli
2. It happens randomly, dometimes it runs for several days, sometimes a few hours only...
3. Using ubuntu server 14.04

**Comment by digidan** [comment] 2016-10-22 02:33
Same issue for me running on latest version of OS X started happening within the last two versions.

**Comment by krilson** [comment] 2016-10-23 21:36
@digidan Yes I forgot to mention this has also been happening to me for a few versions now, not just the one described above. Today I logged in the server and found the same error again, I did a npm update -g storjshare-cli just now, will see it it happens again. 

Current version: 
StorjShare: 7.0.3
Core:       4.1.0
Protocol:   0.9.1

**Comment by benlake** [comment] 2016-10-25 02:43
Same. OSX 10.11.6 (15G1004)

Storj Share 2.0.12
Core Library 4.1.0
Protocol 0.9.1

![screen shot 2016-10-24 at 7 04 23 pm](https://cloud.githubusercontent.com/assets/764685/19671208/ba2325de-9a32-11e6-8c68-8f66ca762066.png)

**Comment by fronck** [comment] 2016-11-02 14:06
I'm seeing this issue on Gentoo / Linux 4.1.15 / nodejs v4.6.1 with this Storj setup:
StorjShare: 7.0.3
Core:       4.1.0
Protocol:   0.9.1

Let me know if I can help by providing log traces or anything else to help out.

**Comment by spiccioli** [comment] 2016-11-14 13:52
Same issue here: CentOS 6.7, ulimit -n at 16K files. 

It seems though that this is a "common" issue with node.js when file handles are not properly handled and closing them is left to node.js' GC.

See: https://github.com/isaacs/node-graceful-fs

**Comment by spiccioli** [comment] 2016-11-16 16:48
I did try adding the little code snippet from here

http://stackoverflow.com/questions/30674757/running-garbage-collection-manually-in-node

(to call the GC from time to time) to /usr/local/bin/stojshare's start function, but it made no difference. It still dies several times each day because of file handles exhaustion.

**Comment by krilson** [comment] 2016-11-22 09:38
This might be the solution, testing now:
(Ubuntu Sever 14.04)
Created a new user just for the storjshare-cli process: 
`sudo adduser storj`

And then:
`su root`
`echo "storj hard nofile 100000" >> /etc/security/limits.conf`
`echo "storj soft nofile 100000" >> /etc/security/limits.conf`
(for some reason the above two comands will not execute with sudo, has to be run via: su root)

Run storjshare-cli in screen under the newly created user.

**Comment by yuilleb** [comment] 2016-11-22 18:04
This problem is caused by kfs not closing leveldb files. The issue is open here: https://github.com/Storj/kfs/issues/38. `scandir` is just reporting that it's unable to acquire a new file descriptor, because they've all be exhausted by kfs.

**Comment by super3** [comment] 2017-01-16 19:02
@yuilleb @krilson @spiccioli @fronck @benlake @digidan Since this appears to be a KFS issue, and storjshare-cli is deprecated going to close.

**Comment by super3** [comment] 2017-01-16 19:02
Please follow this issue there.

**Closed by super3** 2017-01-16 19:02 UTC
Labels: bug
