### ISSUE TITLE
storjshare cli multi-cpu and multi-nodeid support

### ISSUE THREAD

**Issue by 1credit** [Storj/storjshare-cli#149] opened 2016-08-09 22:22 UTC
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
StorjShare:  5.0.2
Core:          2.1.1
Protocol:     0.7.1
```

Replace the values below using the output from `node --version`.

```
v4.4.6
```
### Expected Behavior

Seek the ability to support multiple nodeids in a single instance of StorjShare, much in the way the Windows GUI provides such support.  Ideally StorjShare would be enhanced to spawn separate processes per nodeid or via some other technique become capability of using a specified number of CPU cores on multi-core systems.  I would not anticipate such a request to exceed one core per nodeid, however multiple nodeids may well be requested per core.  If a parameterized core count was supported, this would be of value to GUI users also, allowing them to select (and perhaps defaulting too), N-1 cores on a N-Core system.  This would assure some CPU processing capabilities for the GUI environment and reduce the possibility of Storj oriented resource contention problems for both desktop and server storage environments.   Common aspects, such as address, network & tunnel port, telemetry, and concurrency parameters should be shared across all instances and only need to be specified one time in the new config.json file.  Once implemented, future enhancements could include network port count and bandwidth throttling to assure Storj remains on peoples "Good Behavior" applications lists.  Such future enhancements would be extremely difficult to implement on servers using the current approach of running separate, independent, StorjShare instances.
### Actual Behavior

Currently if one wants to utilize more than one core on a system, one has to run multiple copies of storjshare pointing at unique directories.  Each directory contains its down config.json and related port, tunnel, concurrency, etc. setting.

Currently if one wants to use space on separate directory structures, one has to run multiple copies of storjshare pointing at unique directories.  Each directory contains its down config.json and related port, tunnel, concurrency, etc. setting.

Currently if one wants to maximum utilization of a multi-core environment,  one needs to run multiple copiesof storjshare pointing at unique directories.  Each directory contains its down config.json and related port, tunnel, concurrency, etc. setting.  Balance is only achieved by long, methodical testing of the addition and removal of quantities of nodes.  This is both time consuming, and in the case of node count reduction, results in the orphaning of shards.

```

```
### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.
1. ...
2. ...
3. ...

**Comment by super3** [comment] 2016-08-10 14:15
This is a duplicate of https://github.com/Storj/storjshare-gui/issues/259 in the GUI, which is currently being worked on. We will leave this open for now, since that issue is for the GUI and this is for the CLI.

**Comment by super3** [comment] 2017-01-13 17:04
I believe both of these are implemented in https://github.com/Storj/storjshare-daemon.

**Closed by super3** 2017-01-13 17:04 UTC
Labels: feature
