### ISSUE TITLE
Linux reporting martian sources and possible SYN flooding

### ISSUE THREAD

**Issue by 1credit** [Storj/storjshare-cli#130] opened 2016-07-22 04:09 UTC
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
StorjShare:  5.0.0
Core:          2.0.0
Protocol:     0.7.1
```

Replace the values below using the output from `node --version`.

```
v4.4,6
```

### Expected Behavior

No DMSG output from Storj related activity

### Actual Behavior

[388241.755493] net_ratelimit: 90 callbacks suppressed
[388241.755498] IPv4: martian source 10.184.155.136 from 37.35.96.16, on dev eth0
[388241.755501] ll header: 00000000: 00 24 1d d6 0e de 80 2a a8 4c 61 60 08 00        .$.....*.La`..
[388241.767913] IPv4: martian source 10.184.155.136 from 37.35.96.23, on dev eth0
[388241.767921] ll header: 00000000: 00 24 1d d6 0e de 80 2a a8 4c 61 60 08 00        .$.....*.La`..
[388241.797443] IPv4: martian source 10.184.155.136 from 37.35.96.20, on dev eth0
[388241.797451] ll header: 00000000: 00 24 1d d6 0e de 80 2a a8 4c 61 60 08 00        .$.....*.La`..
[388241.990814] IPv4: martian source 10.184.155.136 from 5.9.94.67, on dev eth0
[388241.990820] ll header: 00000000: 00 24 1d d6 0e de 80 2a a8 4c 61 60 08 00        .$.....*.La`..
[388242.013221] IPv4: martian source 10.184.155.136 from 37.35.96.15, on dev eth0
[388242.013227] ll header: 00000000: 00 24 1d d6 0e de 80 2a a8 4c 61 60 08 00        .$.....*.La`..
[388242.014098] IPv4: martian source 10.184.155.136 from 37.35.96.15, on dev eth0
[388242.014101] ll header: 00000000: 00 24 1d d6 0e de 80 2a a8 4c 61 60 08 00        .$.....*.La`..
[388242.194437] IPv4: martian source 10.184.155.136 from 37.35.96.23, on dev eth0
[388242.194444] ll header: 00000000: 00 24 1d d6 0e de 80 2a a8 4c 61 60 08 00        .$.....*.La`..
[388242.292601] IPv4: martian source 10.184.155.136 from 141.100.73.210, on dev eth0
[388242.292609] ll header: 00000000: 00 24 1d d6 0e de 80 2a a8 4c 61 60 08 00        .$.....*.La`..
[388242.308683] IPv4: martian source 10.184.155.136 from 37.35.96.23, on dev eth0
[388242.308691] ll header: 00000000: 00 24 1d d6 0e de 80 2a a8 4c 61 60 08 00        .$.....*.La`..
[388242.354112] IPv4: martian source 10.184.155.136 from 37.35.96.15, on dev eth0
[388242.354121] ll header: 00000000: 00 24 1d d6 0e de 80 2a a8 4c 61 60 08 00        .$.....*.La`..
[513832.375926] TCP: request_sock_TCP: Possible SYN flooding on port 4060. Sending cookies.  Check SNMP counters.

```
Entire dmsg output since boot (boot messages + more of the above) attached.
[synflood.zip](https://github.com/Storj/storjshare-cli/files/377432/synflood.zip)

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

Running 4 nodes on a single server.  Node 0 uses ports 4000-4019, Node 1 uses 4020-4039, Node 3 uses 4040-4059, Node 4 uses 4060-4079

Sample config.json:

{
  "keypath": "/store/storj/node0/id_ecdsa",
  "address": "1CqdxZemsFmg1A9fm3y1hduwqF5wzBAyKJ",
  "storage": {
    "path": "/store/storj/node0",
    "size": 2,
    "unit": "TB"
  },
  "network": {
    "address": "fspoe.carpenter-farms.us",
    "port": 4000,
    "seeds": [],
    "opcodes": [
      "0f01020202",
      "0f02020202",
      "0f03020202"
    ],
    "forward": false,
    "tunnels": 8,
    "tunnelport": 4001,
    "gateways": {
      "min": 4002,
      "max": 4019
    },
    "concurrency": 3
  },
  "telemetry": {
    "service": "https://status.storj.io",
    "enabled": true
  },
  "loglevel": 3
}

Noticed after seeing that 2 of 4 nodes had crashed.  Node log files attached (both in the one zip)
[node2.zip](https://github.com/Storj/storjshare-cli/files/377433/node2.zip)

**Comment by bookchin** [comment] 2016-08-04 22:01
Off hand, the only reason that @aleitner and I can think of why there may be reported martian sources is that if you are running your 4 nodes on the same host, they may end up communicating with one another while on their respective public IPs.

Based on my limited knowledge of how a martian source is detected or why that message is triggered, this may not be the case.

**Comment by super3** [comment] 2016-09-14 19:25
@1credit Did you get anywhere with this issue?

**Comment by 1credit** [comment] 2016-09-14 20:02
I think Bookchin's theory is likely, which means core#317 would fix it, if implimented as suggested.

That said, I just spot checked a couple of systems and did not see any martian reports.

**Comment by super3** [comment] 2016-09-14 20:04
@1credit So can't reproduce the issue?

**Comment by 1credit** [comment] 2016-09-14 20:12
Most of my systems have been rebooted recently, so I don't have a lot of log files to review.

**Comment by super3** [comment] 2016-09-15 19:59
Please review your logs. Like to close this if it can't be reproduced.

**Closed** 2016-10-14 19:50 UTC
Labels: discussion
