### ISSUE TITLE
Memory usage spikes and storj crashes when storing 200GB on arm

### ISSUE THREAD

**Issue by lazerdye** [Storj/storjshare-cli#169] opened 2016-09-03 10:49 UTC
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
StorjShare: 6.0.2
Core:       3.1.0
Protocol:   0.8.0
```

Replace the values below using the output from `node --version`.

```
v4.4.4
```

### Expected Behavior

Expected storj to run continuously without crashing.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```

I have storj running on a Arm box with 2GB of memory:
Linux cdroid 3.10.102-odroidxu4 #6 SMP PREEMPT Tue Jul 5 17:40:44 CEST 2016 armv7l GNU/Linux

After 10-15 hours, usage of the storj binary jumps to over 1GB:

Tasks: 153 total,   2 running, 151 sleeping,   0 stopped,   0 zombie
%Cpu(s): 11.6 us,  3.6 sy,  0.0 ni, 66.4 id, 18.1 wa,  0.0 hi,  0.4 si,  0.0 st
KiB Mem:   2038640 total,  1932672 used,   105968 free,    13620 buffers
KiB Swap:   131068 total,    57312 used,    73756 free.   246952 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 9397 storj     20   0 1388620 1.221g  11124 S  11.2 62.8 205:47.70 node

Usually it stops without any error logging, but sometime I receive an error like this:

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

<--- Last few GCs --->

45546695 ms: Mark-sweep 697.6 (738.5) -> 697.6 (738.5) MB, 9236.2 / 21 ms [allocation failure] [GC in old space requested].
45555910 ms: Mark-sweep 697.6 (738.5) -> 697.6 (738.5) MB, 9214.9 / 21 ms [allocation failure] [GC in old space requested].
45565186 ms: Mark-sweep 697.6 (738.5) -> 697.6 (737.5) MB, 9275.8 / 21 ms [last resort gc].
45574438 ms: Mark-sweep 697.6 (737.5) -> 697.6 (738.5) MB, 9252.4 / 21 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x3b46d6d9 <JS Object>
    1: join [native array.js:~333] [pc=0x6a0269f0] (this=0x4c06d689 <JS Array[6]>,C=0x44dfe741 <String[1]: />)
    2: join [path.js:~475] [pc=0x69e512a0] (this=0x2ba77fc9 <an Object with map 0x3e0135d5>)
    3: arguments adaptor frame: 2->0
    4: /* anonymous */(aka /* anonymous */) [/opt/storj/storjshare-cli/lib/utils.js:60] [pc=0x3e237dfc] (this=0x3b4080dd <undefined>,diritem=0x6d0c2dd9 <String[...

I lowered the max memory from 250GB to 200GB, it's still taking up 250GB for now:

{"type":"info","message":"telemetry report {\"storage\":{\"free\":-43369412181,\"used\":204430685781},\"bandwidth\":{\"upload\":5.23,\"download\":15.94},\"contact\":{\"protocol\":\"0.8.0\",\"address\":\"storj.lazerdye.org\",\"port\":4020,\"nodeID\":\"fc34009c444f82d7c20d024bccfc90bf0945aebf\",\"lastSeen\":1472894795418},\"payment\":\"17uHyYdwoEQa4F1ViZ39sxChvC3qDWtZ1J\"}","timestamp":"2016-09-03T10:45:15.724Z"}

Also note, I have two other instances running configured to 100GB and they are not (yet) crashing.
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Configure any start up storj on an ARM box with 2GB of memory.
2. Run it long enough to contain over 200GB of shards.
3. Wait for it to crash.

**Comment by deadgray** [comment] 2016-09-05 20:45
I can share my own experience... I had 700GB of shards on my Odroid-C2 (2GB of RAM too, I see you have XU4) and it was running okay. AFAIR storjshare-cli was using 500-700MB.

**Comment by lazerdye** [comment] 2016-09-06 08:06
Cool, the Odroid-C2 is 64bit, which might make a difference. Which OS are you running?

**Comment by super3** [comment] 2016-09-09 15:09
@lazerdye This is caused by our use of LevelDB, which doesn't scale over 100GB (after that things just degrade into errors like this). We have build a solution to this called [KFS](https://github.com/bookchin/kfs). As such this is a duplicate of https://github.com/Storj/core/issues/143, which will solve the error you are experiencing.

**Closed by super3** 2016-09-09 15:09 UTC
