### ISSUE TITLE
Bandwidth limit

### ISSUE THREAD

**Issue by alphaonex86** [Storj/storjshare-cli#150] opened 2016-08-11 18:16 UTC
### Package Versions

```
StorjShare: 5.0.2
Core:       2.1.1
Protocol:   0.7.1
```

```
v4.4.1
```
### Expected Behavior

Have an option to limit the bandwidth, one for download and one for upload rate.
### Actual Behavior

Use all the bandwidth.

**Comment by super3** [comment] 2016-08-24 13:01
Duplicate of https://github.com/Storj/storjshare-gui/issues/281 and #361

There are a dozen 3rd party tools that do this already. 
Windows: Net Balancer
Mac: Waterroof or Noobproof
Linux: Wondershaper

**Comment by super3** [comment] 2016-08-24 13:04
@bookchin How do you want to handle this? There are already 3rd party tools for every platform to do this now. We should probably add it as a feature before the end of the year, because it is a highly requested feature. 

What is time/complexity of building something like this now?

**Comment by alphaonex86** [comment] 2016-08-24 14:25
None work here (Linux ARM and special virtualisation case), I need integrated option, not a 3rd party tools. Basicly you need code:https://en.wikipedia.org/wiki/Bandwidth_throttling, in your case it's 1) detect the speed 2) don't send the packet if the speed is over the limit and queue it
You can look into this project: https://github.com/dmolsen/Throttle https://github.com/jhurliman/node-rate-limiter

**Comment by alphaonex86** [comment] 2016-08-24 14:38
Note: most of p2p software include this bandwidth limitation

**Comment by bookchin** [comment] 2016-08-24 15:19
We need to add it eventually, but it's out of scope for the time being. Let's keep this open and revisit later.

**Comment by super3** [comment] 2017-01-13 17:20
@alphaonex86 storjshare-cli is deprecated. I have added your issue to https://github.com/Storj/storjshare-daemon/issues/17.

**Closed by super3** 2017-01-13 17:20 UTC
Labels: feature
